apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: article-subject-sentiment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nhaliscak/article-subject-sentiment.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: article-subject-sentiment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
